version: '3.3'
services: 
  web:
    build: .
    container_name: converter_app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes: 
        - /opt/S/USERS/FIN/Cashiers/Upload:/opt/S/USERS/FIN/Cashiers/Upload
        - /opt/archive/files:/opt/archive/files
        - /opt/posts/files/media/json:/opt/posts/files/media/json
    ports: 
        - "8000:8000"

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  celery-worker:
    build: .
    container_name: celery-worker
    command: celery -A  Converter  worker -B -l INFO
    depends_on: 
      - rabbit
    environment: 
      - CELERY_BROKER=amqp://guest:guest@rabbit:5672
    volumes: 
        - /opt/S/USERS/FIN/Cashiers/Upload:/opt/S/USERS/FIN/Cashiers/Upload
        - /opt/archive/files:/opt/archive/files
        - /opt/posts/files/media/json:/opt/posts/files/media/json

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A Converter beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment: 
      - CELERY_BROKER=amqp://guest:guest@rabbit:5672

